# ملف تكوين Fly.toml

app = "mu-master1"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  API_ID = "25655555"
  API_HASH = "57b330d11c2e758e6e3514ffc586bad5"
  BOT_TOKEN = "7002439220:AAGEKskizmJ9W9l83hiaSuf6LfxmWV3oLio"
  MONGO_DB_URI = "mongodb+srv://islam2005:islam2005@cluster0.rdjot.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
  MUSIC_assistant = "سيمو"
  OWNER_ID = "6908157965"
  STRING_SESSION = ""
  HEROKU_API_KEY = ""
  HEROKU_APP_NAME = ""
  LOG_GROUP_ID = "-1002071277392"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "30s"
    interval = "15s"
    timeout = "2s"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"
